from utils.config_loader import ConfigLoader

ConfigLoader.load_all()

TILESIZE = 32
CHARACTER_SIZE = 26
HITBOXSIZE = 20
HITBOX_WIDTH = 20
HITBOX_HEIGHT = 20
FPS = 60

HEALTH_LAYER = 6

PLAYER_LAYER = 5
PLAYER_HEALTH = 10
PLAYER_SPEED = 5

CONTACT_KNOCKBACK_FORCE = 8
CONTACT_KNOCKBACK_INTERVAL = 15
KNOCKBACK_DECAY = 0.7
KNOCKBACK_DURATION = 16

ENEMY_LAYER = 3
ENEMY_HEALTH = 6
ENEMY_SPEED = 1
ENEMY_KNOCKBACK_FORCE = 6
ENEMY_KNOCKBACK_DECAY = 0.6

SWORD_KNOCKBACK_FORCE = 6
BULLET_KNOCKBACK_FORCE = 4

WEAPON_LAYER = 7

LOOT_ANIMATION_STEP = 5
LOOT_ANIMATION_MAX_ANGLE = 90
LOOT_FLY_DURATION = 30

FOOD_TYPES = ConfigLoader.get("food_types")

WEAPON_TYPES = ConfigLoader.get("weapon_types")

BULLET_SPEED = 8
BULLET_MAX_DISTANCE = 500

BLOCKS_LAYER = 2
GROUND_LAYER = 1

MAP_GENERATOR = "dungeon"

WORLD_SIZE = 3
BIOME_COUNT = 6
WORLD_ZONE_WIDTH = 50
WORLD_ZONE_HEIGHT = 30

DUNGEON_FLOORS = 4
DUNGEON_GRID_WIDTH = 4
DUNGEON_GRID_HEIGHT = 4
ROOMS_PER_FLOOR = 15

FADE_DURATION = 500

FLOOR_THEMES = ConfigLoader.get("floor_themes")

BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
WHITE = (255, 255, 255)
YELLOW = (255, 255, 0)

SPRITE_PLAYER = ConfigLoader.get("sprite_player")
SPRITE_ENEMY = ConfigLoader.get("sprite_enemy")
ENEMY_TYPES = ConfigLoader.get("enemy_types")
SPRITE_EFFECTS = ConfigLoader.get("sprite_effects")
BOSS_CONFIG = ConfigLoader.get("boss_config")
FLOOR_BOSS_CONFIG = ConfigLoader.get("floor_boss_config")
