from typing import Optional, Protocol

from map.room import Room


class DungeonData(Protocol):
    @property
    def rooms(self) -> dict[tuple[int, int], Room]: ...

    @property
    def map_width(self) -> int: ...

    @property
    def map_height(self) -> int: ...

    @property
    def room_tile_width(self) -> int: ...

    @property
    def room_tile_height(self) -> int: ...

    @property
    def wall_thickness(self) -> int: ...

    def generate_floor(self, floor_number: int) -> list[list[str]]: ...

    def set_start_room_visible(self) -> None: ...

    def get_start_position(self) -> tuple[int, int]: ...

    def get_doors(self) -> list[dict]: ...

    def get_room_at(self, tile_x: int, tile_y: int) -> tuple[int, int]: ...

    def get_current_room(self, tile_x: int, tile_y: int) -> Optional[Room]: ...

    def get_boss_position(self) -> Optional[tuple[int, int]]: ...

    def get_event_position(self) -> Optional[tuple[int, int]]: ...
